### ISSUE TITLE
SPARQL endpoint over http?

### ISSUE THREAD

**Issue by JervenBolleman** [JervenBolleman/spodgi#12]
The current code is command line only. We would need an rdflib based sparql endpoint to make these pangenomes available on the semantic web.

**Comment by suryatejreddy** [comment]
Hey, I would like to work on this issue. Are there any specific guidelines that I should follow before working on this? I am currently exploring the best ways to do this using rdflib. I'll update my findings here.

**Comment by JervenBolleman** [comment]
@suryatejreddy thanks, I was looking at rdflib-web as one option. But was also suggested to use https://github.com/rdflib/pyLDAPI.

No need to follow any guidelines.
