### ISSUE TITLE
If path names have real IRI's then the "IRI denotes a path' hack does not work.

### ISSUE THREAD

**Issue by JervenBolleman** [JervenBolleman/spodgi#17]
This impacts ttl and sparql logic.

**Comment by JervenBolleman** [comment]
[OdgiStore.py#L123](https://github.com/pangenome/spodgi/blob/f182a7b26ee16a9f639df525b439a0601576321d/spodgi/OdgiStore.py#L123)
and [OdgiStore.py#L227](https://github.com/pangenome/spodgi/blob/f182a7b26ee16a9f639df525b439a0601576321d/spodgi/OdgiStore.py#L227)

This code needs to become a function and take into account that realpath names can have '/' in them.

**Comment by subwaystation** [comment]
I took a look at the code mentioned above, but it still looks the same to me? How did you fix the problem?
